#!/bin/sh
source ${MODULESHOME}/init/bash
module use /sw/tools/smithy/modulefiles
module load smithy

export GEM_HOME=/sw/tools/smithy
gem uninstall software_smithy --all --executables
gem install pkg/software_smithy-*.gem
sed -i 's/#!\/.*/#!\/usr\/bin\/env ruby/g' /sw/tools/smithy/bin/*

cp -rv modulefiles /sw/tools/smithy/
cp -rv environment.sh /sw/tools/smithy/

export GEM_HOME=$HOME/.gem/ruby/1.9.1
