#!/bin/sh
bundle exec smithy rdoc
bundle exec ronn man/smithy.1.ronn
bundle exec rake rerdoc
bundle exec rake repackage

source ${MODULESHOME}/init/bash
module use /sw/tools/smithy/modulefiles
module load smithy

export GEM_HOME=/sw/tools/smithy
gem uninstall software_smithy --all --executables
gem install pkg/software_smithy-*.gem
sed -i 's/#!\/.*/#!\/usr\/bin\/env ruby/g' /sw/tools/smithy/bin/*

export GEM_HOME=$HOME/.gem/ruby/1.9.1
