#!/bin/sh
SMITHY_DIR=/sw/tools/smithy

cp -rv modulefiles $SMITHY_DIR/
cp -rv environment.sh $SMITHY_DIR/

source ${MODULESHOME}/init/bash
module use $SMITHY_DIR/modulefiles
module load smithy

export GEM_HOME=$SMITHY_DIR
gem uninstall software_smithy --all --executables
gem install pkg/software_smithy-*.gem
sed -i 's/#!\/.*/#!\/usr\/bin\/env ruby/g' $SMITHY_DIR/bin/*

export GEM_HOME=$HOME/.gem/ruby/1.9.1
