#!/bin/bash
RUBY_INSTALL_DIR=/sw/smoky
RUBY_BUILD_NAME=sles11.1_gnu4.3.2

RUBY_PREFIX=$RUBY_INSTALL_DIR/ruby/1.9.3/$RUBY_BUILD_NAME

echo "==> Installing Ruby"
rm -rf ruby
tar xf ruby.tar
sed -i "s#set PREFIX.*#set PREFIX $RUBY_PREFIX#g" ruby/ruby/1.9.3/modulefile/ruby/1.9.3

mkdir -p $RUBY_INSTALL_DIR
cp -r ruby/ruby $RUBY_INSTALL_DIR/

mkdir -p $RUBY_INSTALL_DIR/modulefiles
cp -rv $RUBY_INSTALL_DIR/ruby/1.9.3/modulefile/ruby $RUBY_INSTALL_DIR/modulefiles/

cd $RUBY_INSTALL_DIR/ruby/1.9.3
mv build $RUBY_BUILD_NAME
cd $RUBY_PREFIX
export SMITHY_PREFIX=`pwd`
./rebuild

