#!/bin/bash
SW_ROOT=/sw
SMITHY_DIR=$SW_ROOT/tools/smithy
RUBY_INSTALL_DIR=$SW_ROOT/xt
RUBY_BUILD_NAME=rhel6.3_gnu4.3.2

RUBY_PREFIX=$RUBY_INSTALL_DIR/ruby/1.9.3/$RUBY_BUILD_NAME
STARTING_DIR=`pwd`

echo "==> Installing Ruby"
rm -rf ruby
tar xf ruby.tar
sed -i "s#set PREFIX.*#set PREFIX $RUBY_PREFIX#g" ruby/ruby/1.9.3/modulefile/ruby/1.9.3

mkdir -p $RUBY_INSTALL_DIR
cp -r ruby/ruby $RUBY_INSTALL_DIR/

mkdir -p $RUBY_INSTALL_DIR/modulefiles
cp -rv $RUBY_INSTALL_DIR/ruby/1.9.3/modulefile/ruby $RUBY_INSTALL_DIR/modulefiles/

cd $RUBY_INSTALL_DIR/ruby/1.9.3
mv build $RUBY_BUILD_NAME
cd $RUBY_PREFIX
export SMITHY_PREFIX=`pwd`
./rebuild

echo "==> Installing Smithy"
cd $STARTING_DIR
rm -rf smithy
tar xf smithy.tar
cd smithy

for f in "environment.sh" "modulefiles/smithy/1.0"
do
  sed -i "s#/sw/tools/smithy#$SMITHY_DIR#g" $f
done

mkdir -p $SMITHY_DIR

cp -rv modulefiles $SMITHY_DIR
cp -rv environment.sh $SMITHY_DIR
cp -rv smithyrc $SMITHY_DIR

source ${MODULESHOME}/init/bash
module use $SMITHY_DIR/modulefiles
module load smithy

export GEM_HOME=$SMITHY_DIR
cd gems
gem uninstall software_smithy --all --executables
gem install gli-1.6.0.gem kramdown-0.13.7.gem open4-1.3.0.gem rainbow-1.1.4.gem terminal-table-1.4.4.gem software_smithy-1.0.gem
sed -i 's/#!\/.*/#!\/usr\/bin\/env ruby/g' $SMITHY_DIR/bin/*

export GEM_HOME=$HOME/.gem/ruby/1.9.1

